-- ============================================================================
-- Spring 2026 Reset for Investment Odyssey
-- ============================================================================
-- Wipes all Spring 2025 TAs, sections, students, game data, and leaderboard
-- entries, then seeds the Spring 2026 roster.
--
-- HOW TO RUN
--   Paste the entire file into the Supabase SQL Editor and execute. The
--   migration runs in a single transaction; if any statement fails, nothing
--   is committed.
--
-- WHAT THIS CHANGES
--   * Deletes every row in: leaderboard, game_participants, player_states,
--     game_states, game_sessions, cash_injections, sections.
--   * Deletes every profile with role IN ('ta', 'student').
--   * Inserts 8 Spring 2026 TAs.
--   * Inserts 18 Spring 2026 sections, keyed by registrar enrollment code.
--   * Inserts 624 Spring 2026 students from Passcodes.csv.
--
-- IMPORTANT: Run this in the Supabase SQL Editor (which uses the service
-- role) so RLS policies do not block the deletes/inserts.
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- Step 1: Wipe game data that references profiles/sections via foreign keys.
--         Order matters: cash_injections, game_participants, player_states,
--         and game_states all reference game_sessions, so they must go first.
-- ----------------------------------------------------------------------------
DELETE FROM leaderboard;
DELETE FROM cash_injections;
DELETE FROM game_participants;
DELETE FROM player_states;
DELETE FROM game_states;
DELETE FROM game_sessions;

-- ----------------------------------------------------------------------------
-- Step 2: Clear section pointers on any remaining profiles before deleting
--         the sections themselves.
-- ----------------------------------------------------------------------------
UPDATE profiles SET section_id = NULL WHERE section_id IS NOT NULL;

DELETE FROM sections;

-- ----------------------------------------------------------------------------
-- Step 3: Drop all student and TA profiles. (Any admin/instructor profiles
--         with other roles are preserved.)
-- ----------------------------------------------------------------------------
DELETE FROM profiles WHERE role IN ('ta', 'student');

-- ----------------------------------------------------------------------------
-- Step 4: Ensure sections has an enrollment_code column. The registrar codes
--         (e.g., 13532) are stored there since the primary key is a UUID.
-- ----------------------------------------------------------------------------
ALTER TABLE sections ADD COLUMN IF NOT EXISTS enrollment_code TEXT;

-- ----------------------------------------------------------------------------
-- Step 5: Seed Spring 2026 TAs and sections in one CTE so section.ta_id
--         lines up with the just-inserted TA UUIDs.
-- ----------------------------------------------------------------------------
WITH ta_data(custom_id, name, passcode) AS (
    VALUES
        ('xinranbai',      'Xinran Bai',      'baiecon2'),
        ('jamesbolyard',   'James Bolyard',   'bolyardecon2'),
        ('yuxincai',       'Yuxin Cai',       'caiecon2'),
        ('zacharyhayward', 'Zachary Hayward', 'haywardecon2'),
        ('mengqili',       'Mengqi Li',       'mengqiliecon2'),
        ('yuanchengli',    'Yuancheng Li',    'yuanchengliecon2'),
        ('stevelin',       'Steve Lin',       'linecon2'),
        ('ziwang',         'Zi Wang',         'wangecon2')
),
inserted_tas AS (
    INSERT INTO profiles (id, custom_id, name, role, passcode, created_at, last_login)
    SELECT gen_random_uuid(), custom_id, name, 'ta', passcode, NOW(), NOW()
    FROM ta_data
    RETURNING id, name
)
INSERT INTO sections (id, enrollment_code, day, time, location, ta_id)
SELECT gen_random_uuid(), s.enrollment_code, s.day, s.time, s.location, t.id
FROM (VALUES
    -- Tuesday 5:00pm
    ('13532', 'T', '5:00pm-5:50pm',   'Phelps 1425',     'Yuancheng Li'),
    ('13540', 'T', '5:00pm-5:50pm',   'Girvetz 2128',    'Xinran Bai'),
    ('13557', 'T', '5:00pm-5:50pm',   'Phelps 1508',     'Steve Lin'),
    ('13565', 'T', '5:00pm-5:50pm',   'North Hall 1109', 'James Bolyard'),
    -- Tuesday 6:00pm
    ('13672', 'T', '6:00pm-6:50pm',   'North Hall 1109', 'James Bolyard'),
    -- Wednesday 6:00pm
    ('13573', 'W', '6:00pm-6:50pm',   'Arts 1349',       'Xinran Bai'),
    ('13581', 'W', '6:00pm-6:50pm',   'Phelps 1425',     'Yuancheng Li'),
    ('13599', 'W', '6:00pm-6:50pm',   'South Hall 1430', 'Yuxin Cai'),
    ('13607', 'W', '6:00pm-6:50pm',   'Girvetz 2128',    'Mengqi Li'),
    -- Wednesday 7:00pm
    ('13680', 'W', '7:00pm-7:50pm',   'North Hall 1109', 'Yuxin Cai'),
    -- Thursday 6:00pm
    ('13615', 'R', '6:00pm-6:50pm',   'Phelps 1508',     'Mengqi Li'),
    ('13623', 'R', '6:00pm-6:50pm',   'North Hall 1109', 'Zachary Hayward'),
    -- Friday morning
    ('57539', 'F', '9:00am-9:50am',   'Phelps 1508',     'Zi Wang'),
    ('57521', 'F', '10:00am-10:50am', 'Phelps 1508',     'Yuxin Cai'),
    -- Friday 12:00pm
    ('13631', 'F', '12:00pm-12:50pm', 'South Hall 1430', 'Steve Lin'),
    ('13649', 'F', '12:00pm-12:50pm', 'Ellison 2626',    'Mengqi Li'),
    ('13656', 'F', '12:00pm-12:50pm', 'Girvetz 2128',    'Zachary Hayward'),
    ('13664', 'F', '12:00pm-12:50pm', 'Phelps 1508',     'Zi Wang')
) AS s(enrollment_code, day, time, location, ta_name)
JOIN inserted_tas t ON t.name = s.ta_name;

-- ----------------------------------------------------------------------------
-- Step 6: Seed Spring 2026 students. Login uses `name` + `passcode`, so
--         `name` is set to the student's NetID (matches Passcodes.csv).
-- ----------------------------------------------------------------------------
INSERT INTO profiles (id, custom_id, name, role, passcode, created_at, last_login) VALUES
    (gen_random_uuid(), 'gabeacosta', 'gabeacosta', 'student', '53822', NOW(), NOW()),
    (gen_random_uuid(), 'mmadams', 'mmadams', 'student', '82277', NOW(), NOW()),
    (gen_random_uuid(), 'saguado-scheyer', 'saguado-scheyer', 'student', '52466', NOW(), NOW()),
    (gen_random_uuid(), 'erick_aguilar', 'erick_aguilar', 'student', '50823', NOW(), NOW()),
    (gen_random_uuid(), 'emilyahern', 'emilyahern', 'student', '28574', NOW(), NOW()),
    (gen_random_uuid(), 'mikealarcon', 'mikealarcon', 'student', '59729', NOW(), NOW()),
    (gen_random_uuid(), 'savanahaldaba', 'savanahaldaba', 'student', '48299', NOW(), NOW()),
    (gen_random_uuid(), 'marvinalonzo', 'marvinalonzo', 'student', '41298', NOW(), NOW()),
    (gen_random_uuid(), 'balsanafi', 'balsanafi', 'student', '86529', NOW(), NOW()),
    (gen_random_uuid(), 'abdulwahab', 'abdulwahab', 'student', '50462', NOW(), NOW()),
    (gen_random_uuid(), 'allanalvarez', 'allanalvarez', 'student', '97019', NOW(), NOW()),
    (gen_random_uuid(), 'kamanatullah', 'kamanatullah', 'student', '16423', NOW(), NOW()),
    (gen_random_uuid(), 'sydni', 'sydni', 'student', '15052', NOW(), NOW()),
    (gen_random_uuid(), 'bamir', 'bamir', 'student', '56037', NOW(), NOW()),
    (gen_random_uuid(), 'rhiya', 'rhiya', 'student', '86885', NOW(), NOW()),
    (gen_random_uuid(), 'sananda', 'sananda', 'student', '85123', NOW(), NOW()),
    (gen_random_uuid(), 'wancheta', 'wancheta', 'student', '23184', NOW(), NOW()),
    (gen_random_uuid(), 'deaanxhaku', 'deaanxhaku', 'student', '83373', NOW(), NOW()),
    (gen_random_uuid(), 'cristianarevalo', 'cristianarevalo', 'student', '12960', NOW(), NOW()),
    (gen_random_uuid(), 'emmetarikan', 'emmetarikan', 'student', '53150', NOW(), NOW()),
    (gen_random_uuid(), 'tyarnold', 'tyarnold', 'student', '13152', NOW(), NOW()),
    (gen_random_uuid(), 'isabelashbridge', 'isabelashbridge', 'student', '83459', NOW(), NOW()),
    (gen_random_uuid(), 'diegoassali', 'diegoassali', 'student', '52376', NOW(), NOW()),
    (gen_random_uuid(), 'charlieatterholm', 'charlieatterholm', 'student', '54856', NOW(), NOW()),
    (gen_random_uuid(), 'tyauer', 'tyauer', 'student', '99262', NOW(), NOW()),
    (gen_random_uuid(), 'gavinault', 'gavinault', 'student', '20232', NOW(), NOW()),
    (gen_random_uuid(), 'vincentauyoung', 'vincentauyoung', 'student', '39142', NOW(), NOW()),
    (gen_random_uuid(), 'ariyannaavalos', 'ariyannaavalos', 'student', '23248', NOW(), NOW()),
    (gen_random_uuid(), 'aavina', 'aavina', 'student', '85665', NOW(), NOW()),
    (gen_random_uuid(), 'annebaker', 'annebaker', 'student', '71843', NOW(), NOW()),
    (gen_random_uuid(), 'avantibal-prasad', 'avantibal-prasad', 'student', '27662', NOW(), NOW()),
    (gen_random_uuid(), 'noahbalough', 'noahbalough', 'student', '58985', NOW(), NOW()),
    (gen_random_uuid(), 'amandabaptista', 'amandabaptista', 'student', '66371', NOW(), NOW()),
    (gen_random_uuid(), 'rbarba', 'rbarba', 'student', '70868', NOW(), NOW()),
    (gen_random_uuid(), 'dharabarnett', 'dharabarnett', 'student', '36215', NOW(), NOW()),
    (gen_random_uuid(), 'ryanbarr', 'ryanbarr', 'student', '14982', NOW(), NOW()),
    (gen_random_uuid(), 'a_barrera', 'a_barrera', 'student', '80345', NOW(), NOW()),
    (gen_random_uuid(), 'c_barrientos', 'c_barrientos', 'student', '67831', NOW(), NOW()),
    (gen_random_uuid(), 'deceel', 'deceel', 'student', '96154', NOW(), NOW()),
    (gen_random_uuid(), 'hbatnagar', 'hbatnagar', 'student', '70580', NOW(), NOW()),
    (gen_random_uuid(), 'rehanbatra', 'rehanbatra', 'student', '75404', NOW(), NOW()),
    (gen_random_uuid(), 'grantbaxter', 'grantbaxter', 'student', '63473', NOW(), NOW()),
    (gen_random_uuid(), 'sydneybeatty', 'sydneybeatty', 'student', '64301', NOW(), NOW()),
    (gen_random_uuid(), 'ncbeltran', 'ncbeltran', 'student', '42998', NOW(), NOW()),
    (gen_random_uuid(), 'lucabenedetti', 'lucabenedetti', 'student', '80792', NOW(), NOW()),
    (gen_random_uuid(), 'sophiabenner', 'sophiabenner', 'student', '75224', NOW(), NOW()),
    (gen_random_uuid(), 'cbentley', 'cbentley', 'student', '36987', NOW(), NOW()),
    (gen_random_uuid(), 'klarabergman', 'klarabergman', 'student', '11760', NOW(), NOW()),
    (gen_random_uuid(), 'nickbertram', 'nickbertram', 'student', '45409', NOW(), NOW()),
    (gen_random_uuid(), 'brinbezinski', 'brinbezinski', 'student', '70423', NOW(), NOW()),
    (gen_random_uuid(), 'krishbhure', 'krishbhure', 'student', '95773', NOW(), NOW()),
    (gen_random_uuid(), 'averyblum', 'averyblum', 'student', '39797', NOW(), NOW()),
    (gen_random_uuid(), 'madelinebohle', 'madelinebohle', 'student', '34594', NOW(), NOW()),
    (gen_random_uuid(), 'aidanbordador', 'aidanbordador', 'student', '14362', NOW(), NOW()),
    (gen_random_uuid(), 'micahbouchy', 'micahbouchy', 'student', '74595', NOW(), NOW()),
    (gen_random_uuid(), 'mitchellbowen', 'mitchellbowen', 'student', '92582', NOW(), NOW()),
    (gen_random_uuid(), 'ava_boyd', 'ava_boyd', 'student', '64831', NOW(), NOW()),
    (gen_random_uuid(), 'alexbran', 'alexbran', 'student', '12160', NOW(), NOW()),
    (gen_random_uuid(), 'beaubreton', 'beaubreton', 'student', '49163', NOW(), NOW()),
    (gen_random_uuid(), 'pbridges', 'pbridges', 'student', '31160', NOW(), NOW()),
    (gen_random_uuid(), 'winstonbromhead', 'winstonbromhead', 'student', '73404', NOW(), NOW()),
    (gen_random_uuid(), 'cbromstad', 'cbromstad', 'student', '36050', NOW(), NOW()),
    (gen_random_uuid(), 'norabrust', 'norabrust', 'student', '98611', NOW(), NOW()),
    (gen_random_uuid(), 'nicbuhl', 'nicbuhl', 'student', '98909', NOW(), NOW()),
    (gen_random_uuid(), 'ashtonbui', 'ashtonbui', 'student', '14622', NOW(), NOW()),
    (gen_random_uuid(), 'johnbui', 'johnbui', 'student', '67067', NOW(), NOW()),
    (gen_random_uuid(), 'bellabuyanurt', 'bellabuyanurt', 'student', '96961', NOW(), NOW()),
    (gen_random_uuid(), 'evebuzoriute', 'evebuzoriute', 'student', '78309', NOW(), NOW()),
    (gen_random_uuid(), 'botao', 'botao', 'student', '99486', NOW(), NOW()),
    (gen_random_uuid(), 'nicole_cai', 'nicole_cai', 'student', '14025', NOW(), NOW()),
    (gen_random_uuid(), 'janesse', 'janesse', 'student', '77124', NOW(), NOW()),
    (gen_random_uuid(), 'icamberos', 'icamberos', 'student', '21158', NOW(), NOW()),
    (gen_random_uuid(), 'bencampbell', 'bencampbell', 'student', '25994', NOW(), NOW()),
    (gen_random_uuid(), 'josecampos', 'josecampos', 'student', '12748', NOW(), NOW()),
    (gen_random_uuid(), 'dcarreoncervantez', 'dcarreoncervantez', 'student', '23283', NOW(), NOW()),
    (gen_random_uuid(), 'armando_carrillo', 'armando_carrillo', 'student', '46740', NOW(), NOW()),
    (gen_random_uuid(), 'evancarter', 'evancarter', 'student', '38789', NOW(), NOW()),
    (gen_random_uuid(), 'vaughancasey', 'vaughancasey', 'student', '97721', NOW(), NOW()),
    (gen_random_uuid(), 'g_castillo', 'g_castillo', 'student', '49484', NOW(), NOW()),
    (gen_random_uuid(), 'izzycerha', 'izzycerha', 'student', '89534', NOW(), NOW()),
    (gen_random_uuid(), 'emiliocervantes', 'emiliocervantes', 'student', '40323', NOW(), NOW()),
    (gen_random_uuid(), 'kchagarlamudi', 'kchagarlamudi', 'student', '20200', NOW(), NOW()),
    (gen_random_uuid(), 'alecchamon', 'alecchamon', 'student', '78270', NOW(), NOW()),
    (gen_random_uuid(), 'chingman_chang', 'chingman_chang', 'student', '86014', NOW(), NOW()),
    (gen_random_uuid(), 'X318856', 'X318856', 'student', '15956', NOW(), NOW()),
    (gen_random_uuid(), 'tche', 'tche', 'student', '76694', NOW(), NOW()),
    (gen_random_uuid(), 'dchen-wong', 'dchen-wong', 'student', '90250', NOW(), NOW()),
    (gen_random_uuid(), 'evon', 'evon', 'student', '16056', NOW(), NOW()),
    (gen_random_uuid(), 'jchen329', 'jchen329', 'student', '50372', NOW(), NOW()),
    (gen_random_uuid(), 'sicheng_chen', 'sicheng_chen', 'student', '48368', NOW(), NOW()),
    (gen_random_uuid(), 'nicholaschiasson', 'nicholaschiasson', 'student', '21245', NOW(), NOW()),
    (gen_random_uuid(), 'sambat', 'sambat', 'student', '84154', NOW(), NOW()),
    (gen_random_uuid(), 'simon_cho', 'simon_cho', 'student', '20855', NOW(), NOW()),
    (gen_random_uuid(), 'leochu', 'leochu', 'student', '90419', NOW(), NOW()),
    (gen_random_uuid(), 'emchuck', 'emchuck', 'student', '46349', NOW(), NOW()),
    (gen_random_uuid(), 'dixon691', 'dixon691', 'student', '63112', NOW(), NOW()),
    (gen_random_uuid(), 'camryncleaves', 'camryncleaves', 'student', '78599', NOW(), NOW()),
    (gen_random_uuid(), 'ciannacobbins', 'ciannacobbins', 'student', '86865', NOW(), NOW()),
    (gen_random_uuid(), 'avaconn', 'avaconn', 'student', '52268', NOW(), NOW()),
    (gen_random_uuid(), 'bryceconover', 'bryceconover', 'student', '56285', NOW(), NOW()),
    (gen_random_uuid(), 'hannahmichelle', 'hannahmichelle', 'student', '28825', NOW(), NOW()),
    (gen_random_uuid(), 'jonathan_copeland', 'jonathan_copeland', 'student', '28563', NOW(), NOW()),
    (gen_random_uuid(), 'j_corey', 'j_corey', 'student', '70996', NOW(), NOW()),
    (gen_random_uuid(), 'melissacortez', 'melissacortez', 'student', '76723', NOW(), NOW()),
    (gen_random_uuid(), 'charlesdcoyne', 'charlesdcoyne', 'student', '34556', NOW(), NOW()),
    (gen_random_uuid(), 'micahcress', 'micahcress', 'student', '35680', NOW(), NOW()),
    (gen_random_uuid(), 'samcrichton', 'samcrichton', 'student', '10649', NOW(), NOW()),
    (gen_random_uuid(), 'saylorcripe', 'saylorcripe', 'student', '32054', NOW(), NOW()),
    (gen_random_uuid(), 'jaimecruzalvarado', 'jaimecruzalvarado', 'student', '89015', NOW(), NOW()),
    (gen_random_uuid(), 'gael_cruz', 'gael_cruz', 'student', '94007', NOW(), NOW()),
    (gen_random_uuid(), 'alondra_cuevas', 'alondra_cuevas', 'student', '43645', NOW(), NOW()),
    (gen_random_uuid(), 'kayleighcui', 'kayleighcui', 'student', '55836', NOW(), NOW()),
    (gen_random_uuid(), 'tannercummings', 'tannercummings', 'student', '56107', NOW(), NOW()),
    (gen_random_uuid(), 'scunneen', 'scunneen', 'student', '31649', NOW(), NOW()),
    (gen_random_uuid(), 'lailacunningham', 'lailacunningham', 'student', '95029', NOW(), NOW()),
    (gen_random_uuid(), 'aydencurameng', 'aydencurameng', 'student', '52326', NOW(), NOW()),
    (gen_random_uuid(), 'jackdagan', 'jackdagan', 'student', '85606', NOW(), NOW()),
    (gen_random_uuid(), 'jamesdahlen', 'jamesdahlen', 'student', '95404', NOW(), NOW()),
    (gen_random_uuid(), 'wilsondam', 'wilsondam', 'student', '48707', NOW(), NOW()),
    (gen_random_uuid(), 'zdang', 'zdang', 'student', '25391', NOW(), NOW()),
    (gen_random_uuid(), 'bdarin', 'bdarin', 'student', '61817', NOW(), NOW()),
    (gen_random_uuid(), 'gerrit', 'gerrit', 'student', '96625', NOW(), NOW()),
    (gen_random_uuid(), 'nathandavies', 'nathandavies', 'student', '28797', NOW(), NOW()),
    (gen_random_uuid(), 'cdavis-tucker', 'cdavis-tucker', 'student', '88933', NOW(), NOW()),
    (gen_random_uuid(), 'senecadawson', 'senecadawson', 'student', '70795', NOW(), NOW()),
    (gen_random_uuid(), 'c_delacerda', 'c_delacerda', 'student', '13480', NOW(), NOW()),
    (gen_random_uuid(), 'vdelarosaquezada', 'vdelarosaquezada', 'student', '14843', NOW(), NOW()),
    (gen_random_uuid(), 'lucasdepaula', 'lucasdepaula', 'student', '30035', NOW(), NOW()),
    (gen_random_uuid(), 'leahdeduyo', 'leahdeduyo', 'student', '89296', NOW(), NOW()),
    (gen_random_uuid(), 'jakedeharo', 'jakedeharo', 'student', '28528', NOW(), NOW()),
    (gen_random_uuid(), 'jinyue', 'jinyue', 'student', '23616', NOW(), NOW()),
    (gen_random_uuid(), 'adrienderas', 'adrienderas', 'student', '13390', NOW(), NOW()),
    (gen_random_uuid(), 'tysondeveze', 'tysondeveze', 'student', '22991', NOW(), NOW()),
    (gen_random_uuid(), 'pablodibner', 'pablodibner', 'student', '56696', NOW(), NOW()),
    (gen_random_uuid(), 'ryanditanna', 'ryanditanna', 'student', '47054', NOW(), NOW()),
    (gen_random_uuid(), 'morgandobrenski', 'morgandobrenski', 'student', '41980', NOW(), NOW()),
    (gen_random_uuid(), 'mdomingues', 'mdomingues', 'student', '88405', NOW(), NOW()),
    (gen_random_uuid(), 'liamdoten', 'liamdoten', 'student', '13734', NOW(), NOW()),
    (gen_random_uuid(), 'tdow', 'tdow', 'student', '47594', NOW(), NOW()),
    (gen_random_uuid(), 'ruobingdu', 'ruobingdu', 'student', '15939', NOW(), NOW()),
    (gen_random_uuid(), 'bryndudley', 'bryndudley', 'student', '70117', NOW(), NOW()),
    (gen_random_uuid(), 'cassiedugan', 'cassiedugan', 'student', '15622', NOW(), NOW()),
    (gen_random_uuid(), 'coledugan', 'coledugan', 'student', '58368', NOW(), NOW()),
    (gen_random_uuid(), 'anabelduggan', 'anabelduggan', 'student', '73479', NOW(), NOW()),
    (gen_random_uuid(), 'jacksondumas', 'jacksondumas', 'student', '65871', NOW(), NOW()),
    (gen_random_uuid(), 'lilydunn', 'lilydunn', 'student', '11038', NOW(), NOW()),
    (gen_random_uuid(), 'carrnearly', 'carrnearly', 'student', '20145', NOW(), NOW()),
    (gen_random_uuid(), 'chloeeberhardt', 'chloeeberhardt', 'student', '68542', NOW(), NOW()),
    (gen_random_uuid(), 'peytoneberhardt', 'peytoneberhardt', 'student', '79797', NOW(), NOW()),
    (gen_random_uuid(), 'shaneeffgen', 'shaneeffgen', 'student', '20702', NOW(), NOW()),
    (gen_random_uuid(), 'aminelahmadi', 'aminelahmadi', 'student', '99742', NOW(), NOW()),
    (gen_random_uuid(), 'adamelsawaf', 'adamelsawaf', 'student', '13941', NOW(), NOW()),
    (gen_random_uuid(), 'armida', 'armida', 'student', '97428', NOW(), NOW()),
    (gen_random_uuid(), 'anthonyescobar', 'anthonyescobar', 'student', '66000', NOW(), NOW()),
    (gen_random_uuid(), 'jespinoza655', 'jespinoza655', 'student', '48781', NOW(), NOW()),
    (gen_random_uuid(), 'aubreyestrada', 'aubreyestrada', 'student', '28259', NOW(), NOW()),
    (gen_random_uuid(), 'christopherestrella', 'christopherestrella', 'student', '95703', NOW(), NOW()),
    (gen_random_uuid(), 'kellyfang', 'kellyfang', 'student', '83869', NOW(), NOW()),
    (gen_random_uuid(), 'austinfeehan', 'austinfeehan', 'student', '55599', NOW(), NOW()),
    (gen_random_uuid(), 'parkerferguson', 'parkerferguson', 'student', '31984', NOW(), NOW()),
    (gen_random_uuid(), 'faavae', 'faavae', 'student', '10576', NOW(), NOW()),
    (gen_random_uuid(), 'avafilipovic', 'avafilipovic', 'student', '47243', NOW(), NOW()),
    (gen_random_uuid(), 'clarafitch', 'clarafitch', 'student', '24033', NOW(), NOW()),
    (gen_random_uuid(), 'orla', 'orla', 'student', '46978', NOW(), NOW()),
    (gen_random_uuid(), 'cristinaflores', 'cristinaflores', 'student', '38099', NOW(), NOW()),
    (gen_random_uuid(), 'franklinflores', 'franklinflores', 'student', '92463', NOW(), NOW()),
    (gen_random_uuid(), 'elizafowler', 'elizafowler', 'student', '65665', NOW(), NOW()),
    (gen_random_uuid(), 'wfowler', 'wfowler', 'student', '68709', NOW(), NOW()),
    (gen_random_uuid(), 'clairefrank', 'clairefrank', 'student', '74060', NOW(), NOW()),
    (gen_random_uuid(), 'liviafrank', 'liviafrank', 'student', '60384', NOW(), NOW()),
    (gen_random_uuid(), 'beckettfredericks', 'beckettfredericks', 'student', '60363', NOW(), NOW()),
    (gen_random_uuid(), 'havenfryer', 'havenfryer', 'student', '87337', NOW(), NOW()),
    (gen_random_uuid(), 'landonfulcher', 'landonfulcher', 'student', '20718', NOW(), NOW()),
    (gen_random_uuid(), 'gfullerton', 'gfullerton', 'student', '28920', NOW(), NOW()),
    (gen_random_uuid(), 'rmgalardi', 'rmgalardi', 'student', '63160', NOW(), NOW()),
    (gen_random_uuid(), 'timothygalindo', 'timothygalindo', 'student', '92617', NOW(), NOW()),
    (gen_random_uuid(), 'brigettegarcia', 'brigettegarcia', 'student', '97361', NOW(), NOW()),
    (gen_random_uuid(), 'i_garcia', 'i_garcia', 'student', '20734', NOW(), NOW()),
    (gen_random_uuid(), 'montserratgarcia', 'montserratgarcia', 'student', '15030', NOW(), NOW()),
    (gen_random_uuid(), 'j_garner', 'j_garner', 'student', '11162', NOW(), NOW()),
    (gen_random_uuid(), 'charlesgarrett', 'charlesgarrett', 'student', '91991', NOW(), NOW()),
    (gen_random_uuid(), 'maxwell624', 'maxwell624', 'student', '25657', NOW(), NOW()),
    (gen_random_uuid(), 'brooklyngaudio', 'brooklyngaudio', 'student', '98110', NOW(), NOW()),
    (gen_random_uuid(), 'jadegauriat', 'jadegauriat', 'student', '67204', NOW(), NOW()),
    (gen_random_uuid(), 'dgevorgyan', 'dgevorgyan', 'student', '28389', NOW(), NOW()),
    (gen_random_uuid(), 'ameliagiles-pufahl', 'ameliagiles-pufahl', 'student', '56957', NOW(), NOW()),
    (gen_random_uuid(), 'pgilmore', 'pgilmore', 'student', '62060', NOW(), NOW()),
    (gen_random_uuid(), 'lizziegladson-pang', 'lizziegladson-pang', 'student', '96602', NOW(), NOW()),
    (gen_random_uuid(), 'vgodinez', 'vgodinez', 'student', '35935', NOW(), NOW()),
    (gen_random_uuid(), 'vgomezcastellanos', 'vgomezcastellanos', 'student', '20663', NOW(), NOW()),
    (gen_random_uuid(), 'daniela_gomez', 'daniela_gomez', 'student', '36416', NOW(), NOW()),
    (gen_random_uuid(), 'donovangonzalez', 'donovangonzalez', 'student', '84877', NOW(), NOW()),
    (gen_random_uuid(), 'jonathan_gonzalez', 'jonathan_gonzalez', 'student', '93192', NOW(), NOW()),
    (gen_random_uuid(), 'josue_gonzalez', 'josue_gonzalez', 'student', '87470', NOW(), NOW()),
    (gen_random_uuid(), 'mgourlay', 'mgourlay', 'student', '97681', NOW(), NOW()),
    (gen_random_uuid(), 'agraniello', 'agraniello', 'student', '36534', NOW(), NOW()),
    (gen_random_uuid(), 'nathanielgraves', 'nathanielgraves', 'student', '91446', NOW(), NOW()),
    (gen_random_uuid(), 'chgray', 'chgray', 'student', '89108', NOW(), NOW()),
    (gen_random_uuid(), 'paytongreco', 'paytongreco', 'student', '76766', NOW(), NOW()),
    (gen_random_uuid(), 'sevenkgreen', 'sevenkgreen', 'student', '66088', NOW(), NOW()),
    (gen_random_uuid(), 'sophiamgreen', 'sophiamgreen', 'student', '20615', NOW(), NOW()),
    (gen_random_uuid(), 'alecgreenwood', 'alecgreenwood', 'student', '41148', NOW(), NOW()),
    (gen_random_uuid(), 'claygriffin', 'claygriffin', 'student', '71852', NOW(), NOW()),
    (gen_random_uuid(), 'williamgrindall', 'williamgrindall', 'student', '49563', NOW(), NOW()),
    (gen_random_uuid(), 'yixingu', 'yixingu', 'student', '94724', NOW(), NOW()),
    (gen_random_uuid(), 'hgueyikian', 'hgueyikian', 'student', '73980', NOW(), NOW()),
    (gen_random_uuid(), 'madisongustafson', 'madisongustafson', 'student', '53877', NOW(), NOW()),
    (gen_random_uuid(), 'c_gutierrez', 'c_gutierrez', 'student', '63838', NOW(), NOW()),
    (gen_random_uuid(), 'isabella_gutierrez', 'isabella_gutierrez', 'student', '20013', NOW(), NOW()),
    (gen_random_uuid(), 'diegoguzman', 'diegoguzman', 'student', '97968', NOW(), NOW()),
    (gen_random_uuid(), 'reidhabas', 'reidhabas', 'student', '66078', NOW(), NOW()),
    (gen_random_uuid(), 'jeremiahhale', 'jeremiahhale', 'student', '38102', NOW(), NOW()),
    (gen_random_uuid(), 'katehamilton', 'katehamilton', 'student', '34158', NOW(), NOW()),
    (gen_random_uuid(), 'trenthamilton', 'trenthamilton', 'student', '94045', NOW(), NOW()),
    (gen_random_uuid(), 'dongtao_han', 'dongtao_han', 'student', '47531', NOW(), NOW()),
    (gen_random_uuid(), 'matthewhanasab', 'matthewhanasab', 'student', '60996', NOW(), NOW()),
    (gen_random_uuid(), 'mchannum', 'mchannum', 'student', '13263', NOW(), NOW()),
    (gen_random_uuid(), 'suttonharrington', 'suttonharrington', 'student', '66043', NOW(), NOW()),
    (gen_random_uuid(), 'sdharris', 'sdharris', 'student', '22833', NOW(), NOW()),
    (gen_random_uuid(), 'shaycocks', 'shaycocks', 'student', '79800', NOW(), NOW()),
    (gen_random_uuid(), 'yhe398', 'yhe398', 'student', '28892', NOW(), NOW()),
    (gen_random_uuid(), 'rheinemann', 'rheinemann', 'student', '95276', NOW(), NOW()),
    (gen_random_uuid(), 'evelynhenriquez', 'evelynhenriquez', 'student', '93175', NOW(), NOW()),
    (gen_random_uuid(), 'christian14', 'christian14', 'student', '53546', NOW(), NOW()),
    (gen_random_uuid(), 'angel696', 'angel696', 'student', '73773', NOW(), NOW()),
    (gen_random_uuid(), 'aylin_hernandez', 'aylin_hernandez', 'student', '58815', NOW(), NOW()),
    (gen_random_uuid(), 'brooklynhernandez', 'brooklynhernandez', 'student', '80135', NOW(), NOW()),
    (gen_random_uuid(), 'esteban_hernandez', 'esteban_hernandez', 'student', '94024', NOW(), NOW()),
    (gen_random_uuid(), 'amiherrick', 'amiherrick', 'student', '46908', NOW(), NOW()),
    (gen_random_uuid(), 'nataliehiatt', 'nataliehiatt', 'student', '22217', NOW(), NOW()),
    (gen_random_uuid(), 'tjh', 'tjh', 'student', '32317', NOW(), NOW()),
    (gen_random_uuid(), 'michaelho', 'michaelho', 'student', '90018', NOW(), NOW()),
    (gen_random_uuid(), 'brandon_hoang', 'brandon_hoang', 'student', '80152', NOW(), NOW()),
    (gen_random_uuid(), 'tommy_hoffman', 'tommy_hoffman', 'student', '83985', NOW(), NOW()),
    (gen_random_uuid(), 'hopehombrecher', 'hopehombrecher', 'student', '11194', NOW(), NOW()),
    (gen_random_uuid(), 'angelinahou', 'angelinahou', 'student', '89594', NOW(), NOW()),
    (gen_random_uuid(), 'chloe_hu', 'chloe_hu', 'student', '37343', NOW(), NOW()),
    (gen_random_uuid(), 'jadehu', 'jadehu', 'student', '36639', NOW(), NOW()),
    (gen_random_uuid(), 'shu971', 'shu971', 'student', '26715', NOW(), NOW()),
    (gen_random_uuid(), 'charleshuang', 'charleshuang', 'student', '30637', NOW(), NOW()),
    (gen_random_uuid(), 'hirohuang', 'hirohuang', 'student', '31668', NOW(), NOW()),
    (gen_random_uuid(), 'jthubert', 'jthubert', 'student', '18272', NOW(), NOW()),
    (gen_random_uuid(), 'dhunter', 'dhunter', 'student', '92903', NOW(), NOW()),
    (gen_random_uuid(), 'anniehusband', 'anniehusband', 'student', '72569', NOW(), NOW()),
    (gen_random_uuid(), 'eric_huynh', 'eric_huynh', 'student', '72585', NOW(), NOW()),
    (gen_random_uuid(), 'ethanhuynh', 'ethanhuynh', 'student', '81569', NOW(), NOW()),
    (gen_random_uuid(), 'thomashuynh', 'thomashuynh', 'student', '78808', NOW(), NOW()),
    (gen_random_uuid(), 'dylanhwang', 'dylanhwang', 'student', '54726', NOW(), NOW()),
    (gen_random_uuid(), 'kennedyiino', 'kennedyiino', 'student', '26022', NOW(), NOW()),
    (gen_random_uuid(), 'danaim', 'danaim', 'student', '32852', NOW(), NOW()),
    (gen_random_uuid(), 'ianizaguirre', 'ianizaguirre', 'student', '52425', NOW(), NOW()),
    (gen_random_uuid(), 'jackjablon', 'jackjablon', 'student', '75781', NOW(), NOW()),
    (gen_random_uuid(), 'jeremiahjack', 'jeremiahjack', 'student', '51029', NOW(), NOW()),
    (gen_random_uuid(), 'alexandrajackson', 'alexandrajackson', 'student', '32087', NOW(), NOW()),
    (gen_random_uuid(), 'gisellejaramillo', 'gisellejaramillo', 'student', '27324', NOW(), NOW()),
    (gen_random_uuid(), 'jimenez377', 'jimenez377', 'student', '78919', NOW(), NOW()),
    (gen_random_uuid(), 'lizethjimenez', 'lizethjimenez', 'student', '12815', NOW(), NOW()),
    (gen_random_uuid(), 'ljoachin', 'ljoachin', 'student', '84418', NOW(), NOW()),
    (gen_random_uuid(), 'kishimeriel', 'kishimeriel', 'student', '54766', NOW(), NOW()),
    (gen_random_uuid(), 'clyde_jonas', 'clyde_jonas', 'student', '47559', NOW(), NOW()),
    (gen_random_uuid(), 'braydenjones', 'braydenjones', 'student', '57690', NOW(), NOW()),
    (gen_random_uuid(), 'sadiejun', 'sadiejun', 'student', '38965', NOW(), NOW()),
    (gen_random_uuid(), 'christinajunge', 'christinajunge', 'student', '62286', NOW(), NOW()),
    (gen_random_uuid(), 'savannahjurgens', 'savannahjurgens', 'student', '32472', NOW(), NOW()),
    (gen_random_uuid(), 'ekam', 'ekam', 'student', '53576', NOW(), NOW()),
    (gen_random_uuid(), 'ishitakansal', 'ishitakansal', 'student', '23458', NOW(), NOW()),
    (gen_random_uuid(), 'addisonkapur', 'addisonkapur', 'student', '40021', NOW(), NOW()),
    (gen_random_uuid(), 'jkarinov', 'jkarinov', 'student', '25159', NOW(), NOW()),
    (gen_random_uuid(), 'collie', 'collie', 'student', '84253', NOW(), NOW()),
    (gen_random_uuid(), 'leokatanosaka', 'leokatanosaka', 'student', '59498', NOW(), NOW()),
    (gen_random_uuid(), 'finnkawalec', 'finnkawalec', 'student', '97687', NOW(), NOW()),
    (gen_random_uuid(), 'jameskepner', 'jameskepner', 'student', '35162', NOW(), NOW()),
    (gen_random_uuid(), 'alexakeys', 'alexakeys', 'student', '72468', NOW(), NOW()),
    (gen_random_uuid(), 'justinkhan', 'justinkhan', 'student', '21027', NOW(), NOW()),
    (gen_random_uuid(), 'jikim', 'jikim', 'student', '58832', NOW(), NOW()),
    (gen_random_uuid(), 'juliakim', 'juliakim', 'student', '50607', NOW(), NOW()),
    (gen_random_uuid(), 'pauljkim', 'pauljkim', 'student', '99565', NOW(), NOW()),
    (gen_random_uuid(), 'wilsonkim', 'wilsonkim', 'student', '50778', NOW(), NOW()),
    (gen_random_uuid(), 'morgankinnear', 'morgankinnear', 'student', '85146', NOW(), NOW()),
    (gen_random_uuid(), 'kline', 'kline', 'student', '52068', NOW(), NOW()),
    (gen_random_uuid(), 'dylanknab', 'dylanknab', 'student', '71660', NOW(), NOW()),
    (gen_random_uuid(), 'sarakono', 'sarakono', 'student', '49332', NOW(), NOW()),
    (gen_random_uuid(), 'ethankopstein', 'ethankopstein', 'student', '65348', NOW(), NOW()),
    (gen_random_uuid(), 'kovarcik', 'kovarcik', 'student', '18969', NOW(), NOW()),
    (gen_random_uuid(), 'rkraus', 'rkraus', 'student', '81448', NOW(), NOW()),
    (gen_random_uuid(), 'leokrinsky', 'leokrinsky', 'student', '23315', NOW(), NOW()),
    (gen_random_uuid(), 'ethankuo', 'ethankuo', 'student', '70196', NOW(), NOW()),
    (gen_random_uuid(), 'annakyrylenko', 'annakyrylenko', 'student', '22865', NOW(), NOW()),
    (gen_random_uuid(), 'plafogiannis', 'plafogiannis', 'student', '54349', NOW(), NOW()),
    (gen_random_uuid(), 'josephlamkin', 'josephlamkin', 'student', '20200', NOW(), NOW()),
    (gen_random_uuid(), 'dongyi_lan', 'dongyi_lan', 'student', '19300', NOW(), NOW()),
    (gen_random_uuid(), 'paytonland', 'paytonland', 'student', '32632', NOW(), NOW()),
    (gen_random_uuid(), 'sophialang', 'sophialang', 'student', '91838', NOW(), NOW()),
    (gen_random_uuid(), 'jakelatz', 'jakelatz', 'student', '46991', NOW(), NOW()),
    (gen_random_uuid(), 'aleal', 'aleal', 'student', '44608', NOW(), NOW()),
    (gen_random_uuid(), 'vledoult', 'vledoult', 'student', '59461', NOW(), NOW()),
    (gen_random_uuid(), 'jacksonlewis', 'jacksonlewis', 'student', '23143', NOW(), NOW()),
    (gen_random_uuid(), 'becky_li', 'becky_li', 'student', '45048', NOW(), NOW()),
    (gen_random_uuid(), 'boyang_li', 'boyang_li', 'student', '60207', NOW(), NOW()),
    (gen_random_uuid(), 'furui', 'furui', 'student', '79971', NOW(), NOW()),
    (gen_random_uuid(), 'kelly_li', 'kelly_li', 'student', '74319', NOW(), NOW()),
    (gen_random_uuid(), 'xinlan_li', 'xinlan_li', 'student', '43044', NOW(), NOW()),
    (gen_random_uuid(), 'xinyangli', 'xinyangli', 'student', '31344', NOW(), NOW()),
    (gen_random_uuid(), 'alanliao', 'alanliao', 'student', '55428', NOW(), NOW()),
    (gen_random_uuid(), 'xinyuliao', 'xinyuliao', 'student', '45928', NOW(), NOW()),
    (gen_random_uuid(), 'vironikamaria', 'vironikamaria', 'student', '23565', NOW(), NOW()),
    (gen_random_uuid(), 'hlin475', 'hlin475', 'student', '80989', NOW(), NOW()),
    (gen_random_uuid(), 'siyinglin', 'siyinglin', 'student', '34776', NOW(), NOW()),
    (gen_random_uuid(), 'yeejenlin', 'yeejenlin', 'student', '12051', NOW(), NOW()),
    (gen_random_uuid(), 'zhien', 'zhien', 'student', '15028', NOW(), NOW()),
    (gen_random_uuid(), 'codylinn', 'codylinn', 'student', '94296', NOW(), NOW()),
    (gen_random_uuid(), 'llins', 'llins', 'student', '57516', NOW(), NOW()),
    (gen_random_uuid(), 'nlira', 'nlira', 'student', '37003', NOW(), NOW()),
    (gen_random_uuid(), 'olivelitwin', 'olivelitwin', 'student', '93265', NOW(), NOW()),
    (gen_random_uuid(), 'eileen_liu', 'eileen_liu', 'student', '25470', NOW(), NOW()),
    (gen_random_uuid(), 'jingyiliu', 'jingyiliu', 'student', '94250', NOW(), NOW()),
    (gen_random_uuid(), 'kunxi', 'kunxi', 'student', '17972', NOW(), NOW()),
    (gen_random_uuid(), 'liu54', 'liu54', 'student', '94713', NOW(), NOW()),
    (gen_random_uuid(), 'llongacre', 'llongacre', 'student', '61294', NOW(), NOW()),
    (gen_random_uuid(), 'jesseloomis', 'jesseloomis', 'student', '75039', NOW(), NOW()),
    (gen_random_uuid(), 'lopez-gamboa', 'lopez-gamboa', 'student', '26016', NOW(), NOW()),
    (gen_random_uuid(), 'brandonlopez42', 'brandonlopez42', 'student', '65539', NOW(), NOW()),
    (gen_random_uuid(), 'kjl192', 'kjl192', 'student', '92945', NOW(), NOW()),
    (gen_random_uuid(), 'ryland', 'ryland', 'student', '63860', NOW(), NOW()),
    (gen_random_uuid(), 'cadenlu', 'cadenlu', 'student', '96846', NOW(), NOW()),
    (gen_random_uuid(), 'chrislu', 'chrislu', 'student', '42077', NOW(), NOW()),
    (gen_random_uuid(), 'gradylubs', 'gradylubs', 'student', '69795', NOW(), NOW()),
    (gen_random_uuid(), 'cluecht', 'cluecht', 'student', '95412', NOW(), NOW()),
    (gen_random_uuid(), 'jlunarodriguez', 'jlunarodriguez', 'student', '68712', NOW(), NOW()),
    (gen_random_uuid(), 'yaxinluo', 'yaxinluo', 'student', '23532', NOW(), NOW()),
    (gen_random_uuid(), 'jaydenly', 'jaydenly', 'student', '95517', NOW(), NOW()),
    (gen_random_uuid(), 'ellislynch', 'ellislynch', 'student', '39867', NOW(), NOW()),
    (gen_random_uuid(), 'owenlyster', 'owenlyster', 'student', '10649', NOW(), NOW()),
    (gen_random_uuid(), 'augustinema', 'augustinema', 'student', '10662', NOW(), NOW()),
    (gen_random_uuid(), 'e_ma', 'e_ma', 'student', '92561', NOW(), NOW()),
    (gen_random_uuid(), 'tmac', 'tmac', 'student', '21837', NOW(), NOW()),
    (gen_random_uuid(), 'roninmacdonald', 'roninmacdonald', 'student', '83578', NOW(), NOW()),
    (gen_random_uuid(), 'braden_magee', 'braden_magee', 'student', '84501', NOW(), NOW()),
    (gen_random_uuid(), 'benjaminmager', 'benjaminmager', 'student', '91145', NOW(), NOW()),
    (gen_random_uuid(), 'emaldonadosoto', 'emaldonadosoto', 'student', '85576', NOW(), NOW()),
    (gen_random_uuid(), 'delaneymangan', 'delaneymangan', 'student', '74243', NOW(), NOW()),
    (gen_random_uuid(), 'jsmansfield', 'jsmansfield', 'student', '16834', NOW(), NOW()),
    (gen_random_uuid(), 'kmarcelo', 'kmarcelo', 'student', '85241', NOW(), NOW()),
    (gen_random_uuid(), 'olive', 'olive', 'student', '98532', NOW(), NOW()),
    (gen_random_uuid(), 'erikmartinezmartinez', 'erikmartinezmartinez', 'student', '18527', NOW(), NOW()),
    (gen_random_uuid(), 'ambermau', 'ambermau', 'student', '81247', NOW(), NOW()),
    (gen_random_uuid(), 'rooksmaxwell', 'rooksmaxwell', 'student', '15670', NOW(), NOW()),
    (gen_random_uuid(), 'tristanmcclellan', 'tristanmcclellan', 'student', '95383', NOW(), NOW()),
    (gen_random_uuid(), 'ethanmcclung', 'ethanmcclung', 'student', '19748', NOW(), NOW()),
    (gen_random_uuid(), 'maevemccormick', 'maevemccormick', 'student', '97106', NOW(), NOW()),
    (gen_random_uuid(), 'tylermcgrath', 'tylermcgrath', 'student', '54339', NOW(), NOW()),
    (gen_random_uuid(), 'charliemcmahon', 'charliemcmahon', 'student', '68951', NOW(), NOW()),
    (gen_random_uuid(), 'lilymcteer', 'lilymcteer', 'student', '10219', NOW(), NOW()),
    (gen_random_uuid(), 'vmedelortiz', 'vmedelortiz', 'student', '17770', NOW(), NOW()),
    (gen_random_uuid(), 'james_meehan', 'james_meehan', 'student', '23756', NOW(), NOW()),
    (gen_random_uuid(), 'yuhaomei', 'yuhaomei', 'student', '46789', NOW(), NOW()),
    (gen_random_uuid(), 'krista_meier', 'krista_meier', 'student', '57144', NOW(), NOW()),
    (gen_random_uuid(), 'ninameraz', 'ninameraz', 'student', '61190', NOW(), NOW()),
    (gen_random_uuid(), 'anikamermer', 'anikamermer', 'student', '85126', NOW(), NOW()),
    (gen_random_uuid(), 'avimeron', 'avimeron', 'student', '56392', NOW(), NOW()),
    (gen_random_uuid(), 'markusmerriam', 'markusmerriam', 'student', '48690', NOW(), NOW()),
    (gen_random_uuid(), 'j_meza', 'j_meza', 'student', '26526', NOW(), NOW()),
    (gen_random_uuid(), 'chasemiller', 'chasemiller', 'student', '57898', NOW(), NOW()),
    (gen_random_uuid(), 'haileymiller', 'haileymiller', 'student', '54517', NOW(), NOW()),
    (gen_random_uuid(), 'ryanmiller155', 'ryanmiller155', 'student', '83506', NOW(), NOW()),
    (gen_random_uuid(), 'sofiamillerman', 'sofiamillerman', 'student', '21051', NOW(), NOW()),
    (gen_random_uuid(), 'zminor', 'zminor', 'student', '69476', NOW(), NOW()),
    (gen_random_uuid(), 'elianamitchell', 'elianamitchell', 'student', '34528', NOW(), NOW()),
    (gen_random_uuid(), 'dallas', 'dallas', 'student', '40848', NOW(), NOW()),
    (gen_random_uuid(), 'jmontero', 'jmontero', 'student', '18635', NOW(), NOW()),
    (gen_random_uuid(), 'ivanmoore', 'ivanmoore', 'student', '70449', NOW(), NOW()),
    (gen_random_uuid(), 'yanamoraru', 'yanamoraru', 'student', '68505', NOW(), NOW()),
    (gen_random_uuid(), 'cmoreau', 'cmoreau', 'student', '42944', NOW(), NOW()),
    (gen_random_uuid(), 'gmorfin', 'gmorfin', 'student', '62815', NOW(), NOW()),
    (gen_random_uuid(), 'smorgan', 'smorgan', 'student', '77771', NOW(), NOW()),
    (gen_random_uuid(), 'quincymorris-fry', 'quincymorris-fry', 'student', '64929', NOW(), NOW()),
    (gen_random_uuid(), 'darnell', 'darnell', 'student', '52351', NOW(), NOW()),
    (gen_random_uuid(), 'mmungunshagai', 'mmungunshagai', 'student', '56919', NOW(), NOW()),
    (gen_random_uuid(), 'metzlin', 'metzlin', 'student', '20753', NOW(), NOW()),
    (gen_random_uuid(), 'ximenamunoz', 'ximenamunoz', 'student', '92817', NOW(), NOW()),
    (gen_random_uuid(), 'dmurrill-caldwell', 'dmurrill-caldwell', 'student', '12848', NOW(), NOW()),
    (gen_random_uuid(), 'adityanagapudi', 'adityanagapudi', 'student', '97563', NOW(), NOW()),
    (gen_random_uuid(), 'abigailnakano', 'abigailnakano', 'student', '85031', NOW(), NOW()),
    (gen_random_uuid(), 'naya', 'naya', 'student', '17875', NOW(), NOW()),
    (gen_random_uuid(), 'lnewton', 'lnewton', 'student', '74346', NOW(), NOW()),
    (gen_random_uuid(), 'annaqnguyen', 'annaqnguyen', 'student', '98731', NOW(), NOW()),
    (gen_random_uuid(), 'nguyen850', 'nguyen850', 'student', '99034', NOW(), NOW()),
    (gen_random_uuid(), 'r_nguyen', 'r_nguyen', 'student', '77987', NOW(), NOW()),
    (gen_random_uuid(), 'ryanhnguyen', 'ryanhnguyen', 'student', '97347', NOW(), NOW()),
    (gen_random_uuid(), 'sabrinanguyen', 'sabrinanguyen', 'student', '35937', NOW(), NOW()),
    (gen_random_uuid(), 'stevenpnguyen', 'stevenpnguyen', 'student', '37430', NOW(), NOW()),
    (gen_random_uuid(), 'tannguyen', 'tannguyen', 'student', '97916', NOW(), NOW()),
    (gen_random_uuid(), 'nie718', 'nie718', 'student', '24538', NOW(), NOW()),
    (gen_random_uuid(), 'anuno', 'anuno', 'student', '99400', NOW(), NOW()),
    (gen_random_uuid(), 'ethannuttall', 'ethannuttall', 'student', '23553', NOW(), NOW()),
    (gen_random_uuid(), 'ain', 'ain', 'student', '60787', NOW(), NOW()),
    (gen_random_uuid(), 'angeloneil', 'angeloneil', 'student', '30530', NOW(), NOW()),
    (gen_random_uuid(), 'soberto', 'soberto', 'student', '61291', NOW(), NOW()),
    (gen_random_uuid(), 'rohanjacob', 'rohanjacob', 'student', '39267', NOW(), NOW()),
    (gen_random_uuid(), 'jose721', 'jose721', 'student', '47234', NOW(), NOW()),
    (gen_random_uuid(), 'molhiser', 'molhiser', 'student', '81740', NOW(), NOW()),
    (gen_random_uuid(), 'deanolliphant', 'deanolliphant', 'student', '64265', NOW(), NOW()),
    (gen_random_uuid(), 'eolmos', 'eolmos', 'student', '75438', NOW(), NOW()),
    (gen_random_uuid(), 'temiloluwa', 'temiloluwa', 'student', '44834', NOW(), NOW()),
    (gen_random_uuid(), 'jamesoneil', 'jamesoneil', 'student', '59742', NOW(), NOW()),
    (gen_random_uuid(), 'adamorenstein', 'adamorenstein', 'student', '85673', NOW(), NOW()),
    (gen_random_uuid(), 'baleighorgan', 'baleighorgan', 'student', '91040', NOW(), NOW()),
    (gen_random_uuid(), 'mileyortiznoriega', 'mileyortiznoriega', 'student', '45174', NOW(), NOW()),
    (gen_random_uuid(), 'tateosborne', 'tateosborne', 'student', '31000', NOW(), NOW()),
    (gen_random_uuid(), 'morganostrer', 'morganostrer', 'student', '88111', NOW(), NOW()),
    (gen_random_uuid(), 'soraozaki', 'soraozaki', 'student', '18326', NOW(), NOW()),
    (gen_random_uuid(), 'fpaalman', 'fpaalman', 'student', '96215', NOW(), NOW()),
    (gen_random_uuid(), 'nathanpadgette', 'nathanpadgette', 'student', '39925', NOW(), NOW()),
    (gen_random_uuid(), 'hpalmer', 'hpalmer', 'student', '65392', NOW(), NOW()),
    (gen_random_uuid(), 'joshuapaniagua', 'joshuapaniagua', 'student', '11393', NOW(), NOW()),
    (gen_random_uuid(), 'krishnapanjwani', 'krishnapanjwani', 'student', '24530', NOW(), NOW()),
    (gen_random_uuid(), 'jpark171', 'jpark171', 'student', '27987', NOW(), NOW()),
    (gen_random_uuid(), 'avnipatel', 'avnipatel', 'student', '95563', NOW(), NOW()),
    (gen_random_uuid(), 'nirvaan_patel', 'nirvaan_patel', 'student', '34481', NOW(), NOW()),
    (gen_random_uuid(), 'maiapatt', 'maiapatt', 'student', '48604', NOW(), NOW()),
    (gen_random_uuid(), 'maximperes', 'maximperes', 'student', '37660', NOW(), NOW()),
    (gen_random_uuid(), 'cperezhernandez', 'cperezhernandez', 'student', '95019', NOW(), NOW()),
    (gen_random_uuid(), 'eperrone', 'eperrone', 'student', '72649', NOW(), NOW()),
    (gen_random_uuid(), 'dylanperusse', 'dylanperusse', 'student', '96059', NOW(), NOW()),
    (gen_random_uuid(), 'wpessner', 'wpessner', 'student', '64354', NOW(), NOW()),
    (gen_random_uuid(), 'maxpfeifer', 'maxpfeifer', 'student', '14235', NOW(), NOW()),
    (gen_random_uuid(), 'ophillips', 'ophillips', 'student', '95411', NOW(), NOW()),
    (gen_random_uuid(), 'elenapopov', 'elenapopov', 'student', '97719', NOW(), NOW()),
    (gen_random_uuid(), 'kade', 'kade', 'student', '41570', NOW(), NOW()),
    (gen_random_uuid(), 'nikoquan', 'nikoquan', 'student', '52097', NOW(), NOW()),
    (gen_random_uuid(), 'diegoquintanilla', 'diegoquintanilla', 'student', '76606', NOW(), NOW()),
    (gen_random_uuid(), 'pieroquiroz', 'pieroquiroz', 'student', '50017', NOW(), NOW()),
    (gen_random_uuid(), 'sarinarabiee', 'sarinarabiee', 'student', '38369', NOW(), NOW()),
    (gen_random_uuid(), 'cragusa', 'cragusa', 'student', '55233', NOW(), NOW()),
    (gen_random_uuid(), 'yramirezlopez', 'yramirezlopez', 'student', '94248', NOW(), NOW()),
    (gen_random_uuid(), 'izicramirez', 'izicramirez', 'student', '63551', NOW(), NOW()),
    (gen_random_uuid(), 'zahararamirez', 'zahararamirez', 'student', '16266', NOW(), NOW()),
    (gen_random_uuid(), 'nyramos', 'nyramos', 'student', '16917', NOW(), NOW()),
    (gen_random_uuid(), 'e_rangel', 'e_rangel', 'student', '14852', NOW(), NOW()),
    (gen_random_uuid(), 'margaretrea', 'margaretrea', 'student', '33428', NOW(), NOW()),
    (gen_random_uuid(), 'ereinhall', 'ereinhall', 'student', '14388', NOW(), NOW()),
    (gen_random_uuid(), 'sarahrenteria', 'sarahrenteria', 'student', '98723', NOW(), NOW()),
    (gen_random_uuid(), 'andresrestrepo', 'andresrestrepo', 'student', '95935', NOW(), NOW()),
    (gen_random_uuid(), 'sydneyretterer', 'sydneyretterer', 'student', '74481', NOW(), NOW()),
    (gen_random_uuid(), 'jazminireyes', 'jazminireyes', 'student', '46524', NOW(), NOW()),
    (gen_random_uuid(), 'derynrimmer', 'derynrimmer', 'student', '32802', NOW(), NOW()),
    (gen_random_uuid(), 'jennaringer', 'jennaringer', 'student', '54194', NOW(), NOW()),
    (gen_random_uuid(), 'anna_rios', 'anna_rios', 'student', '76261', NOW(), NOW()),
    (gen_random_uuid(), 'melanie_rios', 'melanie_rios', 'student', '99085', NOW(), NOW()),
    (gen_random_uuid(), 'lrivera273', 'lrivera273', 'student', '47677', NOW(), NOW()),
    (gen_random_uuid(), 'chacerobbins', 'chacerobbins', 'student', '43810', NOW(), NOW()),
    (gen_random_uuid(), 'lizzy', 'lizzy', 'student', '77230', NOW(), NOW()),
    (gen_random_uuid(), 'sebastian_rodriguez', 'sebastian_rodriguez', 'student', '14270', NOW(), NOW()),
    (gen_random_uuid(), 'xar', 'xar', 'student', '45819', NOW(), NOW()),
    (gen_random_uuid(), 'philiprogers', 'philiprogers', 'student', '84492', NOW(), NOW()),
    (gen_random_uuid(), 'josuerojas', 'josuerojas', 'student', '91617', NOW(), NOW()),
    (gen_random_uuid(), 'montserratromeo', 'montserratromeo', 'student', '36160', NOW(), NOW()),
    (gen_random_uuid(), 'cromney', 'cromney', 'student', '81874', NOW(), NOW()),
    (gen_random_uuid(), 'ryanrosenthal', 'ryanrosenthal', 'student', '45368', NOW(), NOW()),
    (gen_random_uuid(), 'caris', 'caris', 'student', '11739', NOW(), NOW()),
    (gen_random_uuid(), 'carlotta', 'carlotta', 'student', '88136', NOW(), NOW()),
    (gen_random_uuid(), 'srothstein', 'srothstein', 'student', '26727', NOW(), NOW()),
    (gen_random_uuid(), 'samrounds', 'samrounds', 'student', '97228', NOW(), NOW()),
    (gen_random_uuid(), 'grouveyrol', 'grouveyrol', 'student', '42986', NOW(), NOW()),
    (gen_random_uuid(), 'thomasrudy', 'thomasrudy', 'student', '69807', NOW(), NOW()),
    (gen_random_uuid(), 'nicolasruiz', 'nicolasruiz', 'student', '60028', NOW(), NOW()),
    (gen_random_uuid(), 'bradyruss', 'bradyruss', 'student', '45467', NOW(), NOW()),
    (gen_random_uuid(), 'srustgi', 'srustgi', 'student', '56242', NOW(), NOW()),
    (gen_random_uuid(), 'damiensaab', 'damiensaab', 'student', '76666', NOW(), NOW()),
    (gen_random_uuid(), 'sahakyan', 'sahakyan', 'student', '53759', NOW(), NOW()),
    (gen_random_uuid(), 'yuvrajsahota', 'yuvrajsahota', 'student', '28028', NOW(), NOW()),
    (gen_random_uuid(), 'mayasaibel', 'mayasaibel', 'student', '23670', NOW(), NOW()),
    (gen_random_uuid(), 'osalih', 'osalih', 'student', '37187', NOW(), NOW()),
    (gen_random_uuid(), 'psammis', 'psammis', 'student', '21449', NOW(), NOW()),
    (gen_random_uuid(), 'esanchez122', 'esanchez122', 'student', '81668', NOW(), NOW()),
    (gen_random_uuid(), 'argelia', 'argelia', 'student', '19915', NOW(), NOW()),
    (gen_random_uuid(), 'asanchez787', 'asanchez787', 'student', '14176', NOW(), NOW()),
    (gen_random_uuid(), 'emilyjsanchez', 'emilyjsanchez', 'student', '12441', NOW(), NOW()),
    (gen_random_uuid(), 'jazlynnsanchez', 'jazlynnsanchez', 'student', '28114', NOW(), NOW()),
    (gen_random_uuid(), 'jovanisanchez', 'jovanisanchez', 'student', '68371', NOW(), NOW()),
    (gen_random_uuid(), 'sunyodh', 'sunyodh', 'student', '79822', NOW(), NOW()),
    (gen_random_uuid(), 'asantana', 'asantana', 'student', '55667', NOW(), NOW()),
    (gen_random_uuid(), 'edwinsantiagolopez', 'edwinsantiagolopez', 'student', '95053', NOW(), NOW()),
    (gen_random_uuid(), 'aschneeberger', 'aschneeberger', 'student', '42030', NOW(), NOW()),
    (gen_random_uuid(), 'siennaschneider', 'siennaschneider', 'student', '66625', NOW(), NOW()),
    (gen_random_uuid(), 'pscrivener', 'pscrivener', 'student', '96785', NOW(), NOW()),
    (gen_random_uuid(), 'zsegundo', 'zsegundo', 'student', '52724', NOW(), NOW()),
    (gen_random_uuid(), 'e_segura', 'e_segura', 'student', '10823', NOW(), NOW()),
    (gen_random_uuid(), 'meganselby', 'meganselby', 'student', '56395', NOW(), NOW()),
    (gen_random_uuid(), 'estaseliga', 'estaseliga', 'student', '24410', NOW(), NOW()),
    (gen_random_uuid(), 'owensheetz', 'owensheetz', 'student', '60916', NOW(), NOW()),
    (gen_random_uuid(), 'gagesheklow', 'gagesheklow', 'student', '87241', NOW(), NOW()),
    (gen_random_uuid(), 'qinnishen', 'qinnishen', 'student', '29988', NOW(), NOW()),
    (gen_random_uuid(), 'mshende-ruiz', 'mshende-ruiz', 'student', '20128', NOW(), NOW()),
    (gen_random_uuid(), 'ansar', 'ansar', 'student', '37271', NOW(), NOW()),
    (gen_random_uuid(), 'thomasshi', 'thomasshi', 'student', '46909', NOW(), NOW()),
    (gen_random_uuid(), 'matthewshlesinger', 'matthewshlesinger', 'student', '67587', NOW(), NOW()),
    (gen_random_uuid(), 'parkersindermann', 'parkersindermann', 'student', '78874', NOW(), NOW()),
    (gen_random_uuid(), 'ishansingh', 'ishansingh', 'student', '12765', NOW(), NOW()),
    (gen_random_uuid(), 'caseyslinkard', 'caseyslinkard', 'student', '87179', NOW(), NOW()),
    (gen_random_uuid(), 'aaron_smith', 'aaron_smith', 'student', '64595', NOW(), NOW()),
    (gen_random_uuid(), 'aksmith', 'aksmith', 'student', '98018', NOW(), NOW()),
    (gen_random_uuid(), 'keirasmith', 'keirasmith', 'student', '76278', NOW(), NOW()),
    (gen_random_uuid(), 'kobesmith', 'kobesmith', 'student', '68695', NOW(), NOW()),
    (gen_random_uuid(), 'msnell', 'msnell', 'student', '18688', NOW(), NOW()),
    (gen_random_uuid(), 'hhs', 'hhs', 'student', '62555', NOW(), NOW()),
    (gen_random_uuid(), 'jsobala-crawford', 'jsobala-crawford', 'student', '21131', NOW(), NOW()),
    (gen_random_uuid(), 'jonathansoiza', 'jonathansoiza', 'student', '39535', NOW(), NOW()),
    (gen_random_uuid(), 'jessicason', 'jessicason', 'student', '73449', NOW(), NOW()),
    (gen_random_uuid(), 'siche', 'siche', 'student', '60524', NOW(), NOW()),
    (gen_random_uuid(), 'juliannesoo-hoo', 'juliannesoo-hoo', 'student', '34070', NOW(), NOW()),
    (gen_random_uuid(), 'mateosoto', 'mateosoto', 'student', '29606', NOW(), NOW()),
    (gen_random_uuid(), 'spanedda', 'spanedda', 'student', '30643', NOW(), NOW()),
    (gen_random_uuid(), 'phoebespence', 'phoebespence', 'student', '16329', NOW(), NOW()),
    (gen_random_uuid(), 'leospivak', 'leospivak', 'student', '72128', NOW(), NOW()),
    (gen_random_uuid(), 'lukas_splinter', 'lukas_splinter', 'student', '89016', NOW(), NOW()),
    (gen_random_uuid(), 'sarah_j_spooner', 'sarah_j_spooner', 'student', '63801', NOW(), NOW()),
    (gen_random_uuid(), 'a_spragg', 'a_spragg', 'student', '98440', NOW(), NOW()),
    (gen_random_uuid(), 'miastansfield', 'miastansfield', 'student', '66291', NOW(), NOW()),
    (gen_random_uuid(), 'stellacsteinbach', 'stellacsteinbach', 'student', '44093', NOW(), NOW()),
    (gen_random_uuid(), 'kileystempel', 'kileystempel', 'student', '20784', NOW(), NOW()),
    (gen_random_uuid(), 'jacobstephens', 'jacobstephens', 'student', '99976', NOW(), NOW()),
    (gen_random_uuid(), 'teastock', 'teastock', 'student', '64332', NOW(), NOW()),
    (gen_random_uuid(), 'lanestoddard', 'lanestoddard', 'student', '50071', NOW(), NOW()),
    (gen_random_uuid(), 'davidstonich', 'davidstonich', 'student', '79875', NOW(), NOW()),
    (gen_random_uuid(), 'nickstott', 'nickstott', 'student', '73487', NOW(), NOW()),
    (gen_random_uuid(), 'leilastuart', 'leilastuart', 'student', '15634', NOW(), NOW()),
    (gen_random_uuid(), 'suarez922', 'suarez922', 'student', '35034', NOW(), NOW()),
    (gen_random_uuid(), 'gigisullivan', 'gigisullivan', 'student', '19984', NOW(), NOW()),
    (gen_random_uuid(), 'shaela', 'shaela', 'student', '80767', NOW(), NOW()),
    (gen_random_uuid(), 'maohansun', 'maohansun', 'student', '34618', NOW(), NOW()),
    (gen_random_uuid(), 'vickysun', 'vickysun', 'student', '95796', NOW(), NOW()),
    (gen_random_uuid(), 'csupcamey', 'csupcamey', 'student', '25506', NOW(), NOW()),
    (gen_random_uuid(), 'sidneysyverson', 'sidneysyverson', 'student', '85823', NOW(), NOW()),
    (gen_random_uuid(), 'darwinta', 'darwinta', 'student', '98389', NOW(), NOW()),
    (gen_random_uuid(), 'c_taffe', 'c_taffe', 'student', '58677', NOW(), NOW()),
    (gen_random_uuid(), 'isabelletam', 'isabelletam', 'student', '44891', NOW(), NOW()),
    (gen_random_uuid(), 'logantanaka', 'logantanaka', 'student', '25622', NOW(), NOW()),
    (gen_random_uuid(), 'X318631', 'X318631', 'student', '34004', NOW(), NOW()),
    (gen_random_uuid(), 'katieterrazas', 'katieterrazas', 'student', '86935', NOW(), NOW()),
    (gen_random_uuid(), 'georgiaterrell', 'georgiaterrell', 'student', '64826', NOW(), NOW()),
    (gen_random_uuid(), 'ngochuy', 'ngochuy', 'student', '12605', NOW(), NOW()),
    (gen_random_uuid(), 'elysethai', 'elysethai', 'student', '42662', NOW(), NOW()),
    (gen_random_uuid(), 't_theam', 't_theam', 'student', '43866', NOW(), NOW()),
    (gen_random_uuid(), 'elleriebthomas', 'elleriebthomas', 'student', '90257', NOW(), NOW()),
    (gen_random_uuid(), 'jasontofigh', 'jasontofigh', 'student', '27496', NOW(), NOW()),
    (gen_random_uuid(), 'stomoda', 'stomoda', 'student', '73596', NOW(), NOW()),
    (gen_random_uuid(), 'x_tong', 'x_tong', 'student', '97434', NOW(), NOW()),
    (gen_random_uuid(), 'mtowner', 'mtowner', 'student', '97550', NOW(), NOW()),
    (gen_random_uuid(), 'kevin_tram', 'kevin_tram', 'student', '23514', NOW(), NOW()),
    (gen_random_uuid(), 'c_tran', 'c_tran', 'student', '87778', NOW(), NOW()),
    (gen_random_uuid(), 'madelyn35', 'madelyn35', 'student', '43748', NOW(), NOW()),
    (gen_random_uuid(), 'harveytripp', 'harveytripp', 'student', '23551', NOW(), NOW()),
    (gen_random_uuid(), 'hollytrubee', 'hollytrubee', 'student', '37389', NOW(), NOW()),
    (gen_random_uuid(), 'abeltrujillo', 'abeltrujillo', 'student', '59704', NOW(), NOW()),
    (gen_random_uuid(), 'brynntully', 'brynntully', 'student', '47380', NOW(), NOW()),
    (gen_random_uuid(), 'hughuemura', 'hughuemura', 'student', '65429', NOW(), NOW()),
    (gen_random_uuid(), 'kailavachani', 'kailavachani', 'student', '48321', NOW(), NOW()),
    (gen_random_uuid(), 'vannesavalencia', 'vannesavalencia', 'student', '15704', NOW(), NOW()),
    (gen_random_uuid(), 'kritivamshidhar', 'kritivamshidhar', 'student', '38073', NOW(), NOW()),
    (gen_random_uuid(), 'vvanniekerk', 'vvanniekerk', 'student', '14765', NOW(), NOW()),
    (gen_random_uuid(), 'baileyvanar', 'baileyvanar', 'student', '82945', NOW(), NOW()),
    (gen_random_uuid(), 'gracievarney', 'gracievarney', 'student', '25663', NOW(), NOW()),
    (gen_random_uuid(), 'jvazquezlopez', 'jvazquezlopez', 'student', '84317', NOW(), NOW()),
    (gen_random_uuid(), 'brielleventura', 'brielleventura', 'student', '64845', NOW(), NOW()),
    (gen_random_uuid(), 'cvonbarloewen', 'cvonbarloewen', 'student', '14705', NOW(), NOW()),
    (gen_random_uuid(), 'kvue', 'kvue', 'student', '27252', NOW(), NOW()),
    (gen_random_uuid(), 'lukavyatkin', 'lukavyatkin', 'student', '45142', NOW(), NOW()),
    (gen_random_uuid(), 'codywagner', 'codywagner', 'student', '87997', NOW(), NOW()),
    (gen_random_uuid(), 'mayawalsh', 'mayawalsh', 'student', '43174', NOW(), NOW()),
    (gen_random_uuid(), 'sophiawalters', 'sophiawalters', 'student', '27152', NOW(), NOW()),
    (gen_random_uuid(), 'raynwaltman', 'raynwaltman', 'student', '98862', NOW(), NOW()),
    (gen_random_uuid(), 'cewang', 'cewang', 'student', '65105', NOW(), NOW()),
    (gen_random_uuid(), 'jialewang', 'jialewang', 'student', '92687', NOW(), NOW()),
    (gen_random_uuid(), 'yiru765', 'yiru765', 'student', '30279', NOW(), NOW()),
    (gen_random_uuid(), 'X318514', 'X318514', 'student', '91580', NOW(), NOW()),
    (gen_random_uuid(), 'maxwatada', 'maxwatada', 'student', '54496', NOW(), NOW()),
    (gen_random_uuid(), 'hwauson', 'hwauson', 'student', '86560', NOW(), NOW()),
    (gen_random_uuid(), 's_weber', 's_weber', 'student', '92261', NOW(), NOW()),
    (gen_random_uuid(), 'peytonwehner', 'peytonwehner', 'student', '14696', NOW(), NOW()),
    (gen_random_uuid(), 'wei633', 'wei633', 'student', '50229', NOW(), NOW()),
    (gen_random_uuid(), 'charlotteweitzel', 'charlotteweitzel', 'student', '28990', NOW(), NOW()),
    (gen_random_uuid(), 'isiswen', 'isiswen', 'student', '88032', NOW(), NOW()),
    (gen_random_uuid(), 'emmettwestwick', 'emmettwestwick', 'student', '71767', NOW(), NOW()),
    (gen_random_uuid(), 'zwibisono', 'zwibisono', 'student', '73684', NOW(), NOW()),
    (gen_random_uuid(), 'lwittliff', 'lwittliff', 'student', '71908', NOW(), NOW()),
    (gen_random_uuid(), 'noahwollenweber', 'noahwollenweber', 'student', '91237', NOW(), NOW()),
    (gen_random_uuid(), 'halliewon', 'halliewon', 'student', '84731', NOW(), NOW()),
    (gen_random_uuid(), 'iyw', 'iyw', 'student', '47712', NOW(), NOW()),
    (gen_random_uuid(), 'adamwoodworth', 'adamwoodworth', 'student', '59713', NOW(), NOW()),
    (gen_random_uuid(), 'wu22', 'wu22', 'student', '74888', NOW(), NOW()),
    (gen_random_uuid(), 'wu39', 'wu39', 'student', '96737', NOW(), NOW()),
    (gen_random_uuid(), 'jwu332', 'jwu332', 'student', '25539', NOW(), NOW()),
    (gen_random_uuid(), 'chingmanwu', 'chingmanwu', 'student', '53235', NOW(), NOW()),
    (gen_random_uuid(), 'weiwu', 'weiwu', 'student', '50595', NOW(), NOW()),
    (gen_random_uuid(), 'yunuo', 'yunuo', 'student', '25865', NOW(), NOW()),
    (gen_random_uuid(), 'yuhongxiao', 'yuhongxiao', 'student', '58729', NOW(), NOW()),
    (gen_random_uuid(), 'katexie', 'katexie', 'student', '72302', NOW(), NOW()),
    (gen_random_uuid(), 'shengrui', 'shengrui', 'student', '10777', NOW(), NOW()),
    (gen_random_uuid(), 'wenya', 'wenya', 'student', '53448', NOW(), NOW()),
    (gen_random_uuid(), 'acx', 'acx', 'student', '52491', NOW(), NOW()),
    (gen_random_uuid(), 'yiwen_xu', 'yiwen_xu', 'student', '54587', NOW(), NOW()),
    (gen_random_uuid(), 'yxu1', 'yxu1', 'student', '82243', NOW(), NOW()),
    (gen_random_uuid(), 'haixuanyan', 'haixuanyan', 'student', '24122', NOW(), NOW()),
    (gen_random_uuid(), 'nicyang', 'nicyang', 'student', '30845', NOW(), NOW()),
    (gen_random_uuid(), 'abigailyee', 'abigailyee', 'student', '37846', NOW(), NOW()),
    (gen_random_uuid(), 'tyee', 'tyee', 'student', '19030', NOW(), NOW()),
    (gen_random_uuid(), 'ryleeyetka', 'ryleeyetka', 'student', '87412', NOW(), NOW()),
    (gen_random_uuid(), 'ariayoo', 'ariayoo', 'student', '90940', NOW(), NOW()),
    (gen_random_uuid(), 'charlieyork', 'charlieyork', 'student', '55829', NOW(), NOW()),
    (gen_random_uuid(), 'iay', 'iay', 'student', '53861', NOW(), NOW()),
    (gen_random_uuid(), 'hanszambrano', 'hanszambrano', 'student', '61914', NOW(), NOW()),
    (gen_random_uuid(), 'pzemljic', 'pzemljic', 'student', '34887', NOW(), NOW()),
    (gen_random_uuid(), 'sijiazhan', 'sijiazhan', 'student', '86044', NOW(), NOW()),
    (gen_random_uuid(), 'jack_zhang', 'jack_zhang', 'student', '13118', NOW(), NOW()),
    (gen_random_uuid(), 'patrick_zhang', 'patrick_zhang', 'student', '14118', NOW(), NOW()),
    (gen_random_uuid(), 'yiranzhao', 'yiranzhao', 'student', '35592', NOW(), NOW()),
    (gen_random_uuid(), 'lzheng', 'lzheng', 'student', '12244', NOW(), NOW()),
    (gen_random_uuid(), 'tongyuzhou', 'tongyuzhou', 'student', '49100', NOW(), NOW()),
    (gen_random_uuid(), 'yunxizhou', 'yunxizhou', 'student', '51356', NOW(), NOW()),
    (gen_random_uuid(), 'haomingzhu', 'haomingzhu', 'student', '93826', NOW(), NOW()),
    (gen_random_uuid(), 'nziraknejad', 'nziraknejad', 'student', '98376', NOW(), NOW()),
    (gen_random_uuid(), 's_zou', 's_zou', 'student', '66693', NOW(), NOW()),
    (gen_random_uuid(), 'benjaminzukin', 'benjaminzukin', 'student', '10461', NOW(), NOW());


-- ----------------------------------------------------------------------------
-- Step 7: Sanity checks (these are SELECTs, not state changes).
-- ----------------------------------------------------------------------------
DO $$
DECLARE
    ta_count INTEGER;
    section_count INTEGER;
    student_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO ta_count FROM profiles WHERE role = 'ta';
    SELECT COUNT(*) INTO section_count FROM sections;
    SELECT COUNT(*) INTO student_count FROM profiles WHERE role = 'student';

    RAISE NOTICE 'Spring 2026 seed complete: % TAs, % sections, % students',
        ta_count, section_count, student_count;

    IF ta_count <> 8 THEN
        RAISE EXCEPTION 'Expected 8 TAs, got %', ta_count;
    END IF;
    IF section_count <> 18 THEN
        RAISE EXCEPTION 'Expected 18 sections, got %', section_count;
    END IF;
    IF student_count <> 624 THEN
        RAISE EXCEPTION 'Expected 624 students, got %', student_count;
    END IF;
END $$;

COMMIT;
